services:
  - type: web
    name: readinginmins
    env: python
    plan: free
    buildCommand: 
      - pip install -r requirements.txt
    startCommand: 
      - gunicorn app:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: readinginmins-db
          property: connectionString

  - type: postgresql
    name: readinginmins-db
    plan: free
    properties:
      version: 12
