"""Add summary field to Book model

Revision ID: ea616115af79
Revises: dcbda019ea42
Create Date: 2024-05-26 00:52:00.352625

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ea616115af79'
down_revision = 'dcbda019ea42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_progress')
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('summary', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('reading_time', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('insights', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('key_points', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_column('key_points')
        batch_op.drop_column('insights')
        batch_op.drop_column('reading_time')
        batch_op.drop_column('summary')

    op.create_table('user_progress',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('book_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('chapter_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('progress_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('progress_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], name='user_progress_book_id_fkey'),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapter.id'], name='user_progress_chapter_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='user_progress_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_progress_pkey')
    )
    # ### end Alembic commands ###
